FROM grafana/grafana:13.1.0
COPY provisioning/dashboards /var/lib/grafana/dashboards
COPY provisioning/dashboards/dashboard.yaml /etc/grafana/provisioning/dashboards/dashboard.yaml
COPY provisioning/datasources/datasource.yaml /etc/grafana/provisioning/datasources/datasource.yaml
